Demomoviez/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from movie import urls as movie_url
from movie.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include(movie_url, namespace='movies')),
    path('', HomeView.as_view(), name='home'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path

from .views import MovieList, MovieDetail, MovieCategory, MovieLanguage, MovieSearch, MovieyearView

app_name = 'movie'
urlpatterns = [
    path('', MovieList.as_view(), name='movie_list'),
    path('category/<str:category>/', MovieCategory.as_view(), name='movie_category'),
    path('language/<str:lang>/', MovieLanguage.as_view(), name='movie_language'),
    path('year/<int:year>/', MovieyearView.as_view(), name='movie_year_view'),
    path('search/', MovieSearch.as_view(), name='movie_search'),
    path('<slug:slug>/', MovieDetail.as_view(), name='movie_detail'),
    
]

movie/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
# Create your models here.

CATEGORY_CHOICES = (
    ('action', 'ACTIONS'),
    ('drama', 'DRAMA',),
    ('comedy', 'COMEDY'),
    ('romance', 'ROMANCE')
)

LANGUAGE_CHOICES = (
    ('english', 'ENGLISH'),
    ('hindi', 'HINDI'),
    ('telugu', 'TELUGU'),
    ('tamil', 'TAMIL'),
)

STATUS_CHOICES = (
    ('RA', 'RECENTLY'),
    ('MW', 'MOST WATCHES'),
    ('TR', 'TOP RATED'),
    ('CS', 'COMING SOON'),
)
class Movie(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='movies')
    banner=models.ImageField(upload_to='movies')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=10)
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=10)
    status = models.CharField(choices=STATUS_CHOICES, max_length=2)
    years_of_production = models.DateField()
    views_count = models.IntegerField(default=0)
    cast = models.CharField(max_length=250)
    movie_trailer = models.URLField()
    slug = models.SlugField(blank=True, null=True)
    created = models.DateTimeField(default=timezone.now)
    
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug= slugify(self.title)
        super(Movie, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.title

LINK_CHOICES = (
    ('D', 'DOWNLOAD LINK'),
    ('W', 'WATCH LINK'),
)

class MovieLinks(models.Model):
    movie = models.ForeignKey(Movie, related_name='movie_watch_link', on_delete=models.CASCADE)
    type = models.CharField(choices=LINK_CHOICES, max_length=1)
    link = models.URLField()

    def __str__(self):
        return str(self.movie) + ' ' + str(self.movie)

class DownloadLink(models.Model):
    pass

movie/views.py
from pyexpat import model
from unicodedata import category
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView
from django.views.generic.dates import YearArchiveView
from .models import Movie, MovieLinks

 
class HomeView(ListView):
    model = Movie
    template_name = 'movie/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['top_rated'] = Movie.objects.filter(status='TR')
        context['most_watched'] = Movie.objects.filter(status='MW')
        context['recently_added'] = Movie.objects.filter(status='RA')
        return context


class MovieList(ListView):
    model = Movie
    paginate_by = 10
    
class MovieDetail(DetailView):
    model = Movie
    
    def get_object(self):
        object = super(MovieDetail, self).get_object()
        object.views_count += 1
        object.save()
        return object
    
    def get_context_data(self, **kwargs ):
        context = super(MovieDetail, self).get_context_data(**kwargs)
        context['links'] = MovieLinks.objects.filter(movie=self.get_object())
        context['related_movies'] = Movie.objects.filter(category=self.get_object().category)
        print(context)
        return context
        

class MovieCategory(ListView):
    model = Movie
    paginate_by = 10
    def get_queryset(self):
        self.category = self.kwargs['category']
        return Movie.objects.filter(category=self.category)
        
        
    def get_context_data(self, **kwargs):
        context = super(MovieCategory, self).get_context_data(**kwargs)
        context['movie_category'] = self.category
        
       
        return context

class MovieLanguage(ListView):
    model = Movie
    paginate_by = 10
    
    def get_queryset(self):
        self.language = self.kwargs['lang']
        return Movie.objects.filter(language=self.language)
        
        
    def get_context_data(self, **kwargs):
        context = super(MovieLanguage, self).get_context_data(**kwargs)
        context['movie_language'] = self.language
        return context

class MovieSearch(ListView):
    model = Movie
    paginate_by = 10
    
    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            object_list = Movie.objects.filter(title__icontains=query)
            print(query, object_list)
        else:
            object_list = self.model.objects.none()
        return object_list
  # mylist =[]
  # mylist += [x.title for x in queryset]
  # return JsonResponse(mylist,safe=False)


class MovieyearView(YearArchiveView):
    queryset = Movie.objects.all()
    date_field = 'years_of_production'
    make_object_list = True
    allow_future = True

movie/templates/movie/home.html
{%extends 'base.html'%}
{%load static %}

{%block movielist %}

<section class="portfolio-area pt-60">
	<div class="container">
		
		
		<div class="row flexbox-center">
			<div class="col-lg-6 text-center text-lg-left">
				<div class="section-title">
					<h1><i class="icofont icofont-movie"></i> Most Watches</h1>
				</div>
			</div>
			<div class="col-lg-6 text-center text-lg-right">
				<!-- <div class="portfolio-menu">
					<ul>
						<li data-filter="*" class="active">Latest</li>
						<li data-filter=".soon">Comming Soon</li>
						<li data-filter=".top">Top Rated</li>
						<li data-filter=".released">Recently Released</li>
					</ul>
				</div> -->
			</div>
		</div>
		<hr />
		<div class="row portfolio-item">
			<!-- {%if movie_category%}
				<h3>{{movie_category}}</h3>
			{%endif%}
			{%if movie_language%}
				<h3>{{movie_language}}</h3>
			{%endif%} -->
			{% for movie in most_watched %}

			<div class="col-lg-3 col-md-4 col-sm-6 soon released">
				<div class="single-portfolio">
					<div class="single-portfolio-img">
						<a href="{% url 'movies:movie_detail' movie.slug%}">
							<img src="{{movie.image.url}}" alt="portfolio" />
						</a>
					</div>
					<div class="portfolio-content">
						<h2>{{movie.title}}</h2>
						<div class="review">
							<div class="author-review">
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
							</div>
							<h4>{{movie.views_count}}</h4>
						</div>
					</div>
				</div>
			</div>
			{%empty%}
				<h3> There is no movie in this category</h3>
			{% endfor %}
			
		</div>	
		
		
	</br>
		<div class="row flexbox-center">
			<div class="col-lg-6 text-center text-lg-left">
				<div class="section-title">
					<h1><i class="icofont icofont-movie"></i>Top Rated</h1>
				</div>
			</div>
			<div class="col-lg-6 text-center text-lg-right">
				<!-- <div class="portfolio-menu">
					<ul>
						<li data-filter="*" class="active">Latest</li>
						<li data-filter=".soon">Comming Soon</li>
						<li data-filter=".top">Top Rated</li>
						<li data-filter=".released">Recently Released</li>
					</ul>
				</div> -->
			</div>
		</div>
		<hr />
		<div class="row portfolio-item">
			<!-- {%if movie_category%}
				<h3>{{movie_category}}</h3>
			{%endif%}
			{%if movie_language%}
				<h3>{{movie_language}}</h3>
			{%endif%} -->
			{% for movie in top_rated %}

			<div class="col-lg-3 col-md-4 col-sm-6 soon released">	
				<div class="single-portfolio">
					<div class="single-portfolio-img">
						<a href="{% url 'movies:movie_detail' movie.slug%}">
							<img src="{{movie.image.url}}" alt="portfolio" />
						</a>
					</div>
					<div class="portfolio-content">
						<h2>{{movie.title}}</h2>
						<div class="review">
							<div class="author-review">
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
							</div>
							<h4>{{movie.views_count}}</h4>
						</div>
					</div>	
				</div>	
			</div>
			{%empty%}
				<h3> There is no movie in this category</h3>
			{% endfor %}
		</div>		

		
	</br>
		<div class="row flexbox-center">
			<div class="col-lg-6 text-center text-lg-left">
				<div class="section-title">
					<h1><i class="icofont icofont-movie"></i>Recently Added</h1>
				</div>
			</div>
			<div class="col-lg-6 text-center text-lg-right">
				<!-- <div class="portfolio-menu">
					<ul>
						<li data-filter="*" class="active">Latest</li>
						<li data-filter=".soon">Comming Soon</li>
						<li data-filter=".top">Top Rated</li>
						<li data-filter=".released">Recently Released</li>
					</ul>
				</div> -->
			</div>
		</div>
		<hr />
		<div class="row portfolio-item">
			<!-- {%if movie_category%}
				<h3>{{movie_category}}</h3>
			{%endif%}
			{%if movie_language%}
				<h3>{{movie_language}}</h3>
			{%endif%} -->
			{% for movie in recently_added %}

			<div class="col-lg-3 col-md-4 col-sm-6 soon released">	
				<div class="single-portfolio">
					<div class="single-portfolio-img">
						<a href="{% url 'movies:movie_detail' movie.slug%}">
							<img src="{{movie.image.url}}" alt="portfolio" />
						</a>
					</div>
					<div class="portfolio-content">
						<h2>{{movie.title}}</h2>
						<div class="review">
							<div class="author-review">
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
							</div>
							<h4>{{movie.views_count}}</h4>
						</div>
					</div>	
				</div>	
			</div>
			{%empty%}
				<h3> There is no movie in this category</h3>
			{% endfor %}
		</div>		





	</div>







		<!-- {%if is_paginated%}
			<nav aria-label="Page navigation example" >
				<ul class="pagination justify-content-center">
					{%if page_obj.has_previous %}
						<li><a class="page-link theme-btn" href="?page={{page_obj.previous_page_number}}">prev</a></li>
					{%else%}
					<li class="disabled"></li>
					{%endif%}
					{%for pages in page_obj.paginator.page_range%}
						{%if page_obj.number == pages%}
							<li><a class="page-link theme-btn" href="#">{{pages}}</a></li>
						{%else%}
							<li><a class="page-link theme-btn" href="?page={{pages}}">{{pages}}</a></li>
						{%endif%}
					{%endfor%}
					{%if page_obj.has_next %}
						<li><a class="page-link theme-btn" href="?page={{page_obj.next_page_number}}">next</a></li>
					{%else%}
						<li class="disabled"></li>
					{%endif%}
				</ul>
			</nav>
	{%endif%} -->

</section>

{%endblock movielist %}

movie/templates/movie/movie_archive_year.html
{%extends 'base.html' %}
{%load static %}

{%block movielist %}
<section class="portfolio-area pt-60">
	<div class="container">
		
		<div class="row flexbox-center">
			<div class="col-lg-6 text-center text-lg-left">
				<div class="section-title">
					<h1><i class="icofont icofont-movie"></i> Movie List</h1>
				</div>
			</div>
			<div class="col-lg-6 text-center text-lg-right">
				<div class="portfolio-menu">

				</div>
			</div>
		</div>
		<hr />
		<div class="row portfolio-item">
			{% for movie in object_list %}
			<div class="col-lg-3 col-md-4 col-sm-6 soon released">	
				<div class="single-portfolio">
					<div class="single-portfolio-img">
						<img src="{{movie.image.url}}" alt="portfolio" />
					</div>
					<div class="portfolio-content">
						<h2>{{movie.title}}</h2>
						<div class="review">
							<div class="author-review">
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
							</div>
							<h4>{{movie.views_count}}</h4>
						</div>
					</div>	
				</div>	
			</div>
			{%empty%}
				<h3> There is no movie in this category</h3>
			{% endfor %}
		</div>		
	</div>
		{%if is_paginated%}
			<nav aria-label="Page navigation example" >
				<ul class="pagination justify-content-center">
					{%if page_obj.has_previous %}
						<li><a class="page-link" href="?page={{page_obj.previous_page_number}}">prev</a></li>
					{%else%}
					<li class="disabled"></li>
					{%endif%}
					{%for pages in page_obj.paginator.page_range%}
						{%if page_obj.number == pages%}
							<li><a class="page-link" href="#">{{pages}}</a></li>
						{%else%}
							<li><a class="page-link" href="?page={{pages}}">{{pages}}</a></li>
						{%endif%}
					{%endfor%}
					{%if page_obj.has_next %}
						<li><a class="page-link" href="?page={{page_obj.next_page_number}}">next</a></li>
					{%else%}
						<li class="disabled"></li>
					{%endif%}
				</ul>
			</nav>
	{%endif%}

</section>

{%endblock movielist %}

movie/templates/movie/movie_detail.html
{%extends 'base.html' %}
{%load static %}

{%block details%}

		<!-- transformers area start -->
		<section class="transformers-area">
			<div class="container">
                
				<div class="transformers-box">
					
					<div>
						<h3>Triler</h3>
						<div class="video-area">
							<img src="{{object.banner.url}}" alt="video" />
							<a href="{{object.movie_trailer}}" class="popup-youtube">
								<i class="icofont icofont-ui-play"></i>
							</a>
						</div>
						
					</div>

					<div class="row flexbox-center">
						<div class="col-lg-5 text-lg-left text-center">
							<div class="transformers-content">
								<img src="{{object.image.url}}" alt="about" />
							</div>
						</div>
						<div class="col-lg-7">
							<div class="transformers-content">
								<h2>{{object}}</h2>
								<p>{{object.category}}</p>
								<ul>
									<li>
										<div class="transformers-left">
											Movie:
										</div>
										<div class="transformers-right">
											<a href="#">{{object.category}}</a>
										</div>
									</li>
									<li>
										<div class="transformers-left">
											Cast:
										</div>
										<div class="transformers-right">
											{{object.cast}}
										</div>
									</li>
									<li>
										<div class="transformers-left">
											Director:
										</div>
										<div class="transformers-right">
											***##***
										</div>
									</li>
									<li>
										<div class="transformers-left">
											Time: 
										</div>
										<div class="transformers-right">
											*
										</div>
									</li>
									<li>
										<div class="transformers-left">
											Release:
										</div>
										<div class="transformers-right">
											{{object.years_of_production}}
										</div>
									</li>
									<li>
										<div class="transformers-left">
											Language:
										</div>
										<div class="transformers-right">
											{{object.language}}
										</div>
									</li>
									<li>
										<div class="transformers-left">
											Views
										</div>
										<div class="transformers-right">
											{{object.views_count}}
										</div>
									</li>

									<li>
										<div class="transformers-left">
											Links:
										</div>
										<div class="transformers-right">
											<ul class="dlinks">
                                                {%for link in links%}
                                                    {%if link.type == 'D'%}
                                                        <li><a class="theme-btn" href="{{link.link}}">Download link</a></li>
                                                    {%elif link.type == 'W'%}
                                                        <li><a class="theme-btn" href="{{link.link}}">Watch link</a></li>
                                                    {%endif%}
                                                {%endfor%}
                                            </ul>
										</div>
									</li>
								</ul>
							</div>
						</div>
					</div>

				</div>
			</div>
		</section><!-- transformers area end -->

		<!-- details area start -->
		<section class="details-area">
			<div class="container">
				<div class="row">
					<div class="col-lg-9">
						<div class="details-content">
							<div class="details-overview">
								<h2>Overview</h2>
								<p>{{object.description}}</p>
							</div>
							<div class="details-reply">
								<h2>Leave a Reply</h2>
								<form action="#">
									<div class="row">
										<div class="col-lg-4">
											<div class="select-container">
												<input type="text" placeholder="Name"/>
												<i class="icofont icofont-ui-user"></i>
											</div>
										</div>
										<div class="col-lg-4">
											<div class="select-container">
												<input type="text" placeholder="Email"/>
												<i class="icofont icofont-envelope"></i>
											</div>
										</div>
										<div class="col-lg-4">
											<div class="select-container">
												<input type="text" placeholder="Phone"/>
												<i class="icofont icofont-phone"></i>
											</div>
										</div>
										<div class="col-lg-12">
											<div class="textarea-container">
												<textarea placeholder="Type Here Message"></textarea>
												<button><i class="icofont icofont-send-mail"></i></button>
											</div>
										</div>
									</div>
								</form>
							</div>
							<div class="details-comment">
								<a class="theme-btn theme-btn2" href="#">Post Comment</a>
							</div>
							<div class="details-thumb">
								<div class="details-thumb-prev">
									<div class="thumb-icon">
										<i class="icofont icofont-simple-left"></i>
									</div>
									<div class="thumb-text">
										<h4>Previous Post</h4>
										<p>Standard Post With Gallery</p>
									</div>
								</div>
								<div class="details-thumb-next">
									<div class="thumb-text">
										<h4>Next Post</h4>
										<p>Standard Post With Preview Image</p>
									</div>
									<div class="thumb-icon">
										<i class="icofont icofont-simple-right"></i>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<div class="section-title pb-20">
							<h1><i class="icofont icofont-film"></i> Related Movies</h1>
						</div>
					</div>
				</div>
				<hr />
				<div class="row">
					<div class="col-md-12">
						<div class="video-slider mt-20">
							{%for movie in related_movies%}
							<div class="video-area">
								<img src="{{movie.image.url}}" alt="video" />
								<a href="{{movie.movie_trailer}}" class="popup-youtube">
									<i class="icofont icofont-ui-play"></i>
								</a>
							</div>
							{%endfor%}
						</div>
					</div>
				</div>
			</div>

		</section><!-- details area end -->
{%endblock details%}

movie/templates/movie/movie_list.html
{%extends 'base.html' %}
{%load static %}

{%block movielist %}
<section class="portfolio-area pt-60">
	<div class="container">
		
		
		<div class="row flexbox-center">
			<div class="col-lg-6 text-center text-lg-left">
				<div class="section-title">
					<h1><i class="icofont icofont-movie"></i> Movie List</h1>
				</div>
			</div>
			<div class="col-lg-6 text-center text-lg-right">
			</div>
		</div>
		<hr />
		<div class="row portfolio-item">
			{% for movie in object_list %}
			<div class="col-lg-3 col-md-4 col-sm-6 soon released">	
				<div class="single-portfolio">
					<div class="single-portfolio-img">
						<a href="{% url 'movies:movie_detail' movie.slug%}">
							<img src="{{movie.image.url}}" alt="portfolio" />
						</a>
					</div>
					<div class="portfolio-content">
						<h2>{{movie.title}}</h2>
						<div class="review">
							<div class="author-review">
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
								<i class="icofont icofont-star"></i>
							</div>
							<h4>{{movie.views_count}}</h4>
						</div>
					</div>	
				</div>	
			</div>
			{%empty%}
				<h3> There is no movie in this category</h3>
			{% endfor %}
		</div>		
	</div>
		{%if is_paginated%}
			<nav aria-label="Page navigation example" >
				<ul class="pagination justify-content-center">
					{%if page_obj.has_previous %}
						<li><a class="page-link theme-btn" href="?page={{page_obj.previous_page_number}}">prev</a></li>
					{%else%}
					<li class="disabled"></li>
					{%endif%}
					{%for pages in page_obj.paginator.page_range%}
						{%if page_obj.number == pages%}
							<li><a class="page-link theme-btn" href="#">{{pages}}</a></li>
						{%else%}
							<li><a class="page-link theme-btn" href="?page={{pages}}">{{pages}}</a></li>
						{%endif%}
					{%endfor%}
					{%if page_obj.has_next %}
						<li><a class="page-link theme-btn" href="?page={{page_obj.next_page_number}}">next</a></li>
					{%else%}
						<li class="disabled"></li>
					{%endif%}
				</ul>
			</nav>
	{%endif%}

</section>

{%endblock movielist %}